# Generated by Django 5.2.5 on 2025-08-29 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Folder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        default="Мои документы",
                        help_text="Заполните название папки",
                        max_length=100,
                        verbose_name="Название папки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец папки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Папка",
                "verbose_name_plural": "Папки",
                "unique_together": {("title", "owner")},
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название документа", max_length=200, verbose_name="Название документа"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Введите описание документа", verbose_name="Описание"),
                ),
                ("file", models.FileField(upload_to="documents/%Y/%m/%d/", verbose_name="Файл")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Подтвержден"),
                            ("rejected", "Отклонен"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус документа",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время загрузки документа"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата и время проверки")),
                ("review_comment", models.TextField(blank=True, verbose_name="Комментарий при проверке")),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Укажите владельца документа",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверивший администратор",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="documents.folder",
                        verbose_name="Название папки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
