# Generated by Django 5.2.5 on 2025-09-02 17:49

from django.db import migrations, models

import documents.services


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApprovalQueue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        default="Документы в работе",
                        help_text="Укажите название очереди",
                        max_length=200,
                        verbose_name="Название очереди",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Время и дата создания очереди")),
            ],
            options={
                "verbose_name": "Очередь",
                "verbose_name_plural": "Очереди",
                "ordering": ["approver"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название документа", max_length=200, verbose_name="Название документа"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Введите описание документа", verbose_name="Описание"),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Введите название файла",
                        upload_to='temp_uploads/%Y/%m/%d/',
                        verbose_name="Расположение vs название файла",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("approved", "Подтвержден"),
                            ("rejected", "Отклонен"),
                            ("archived", "В архиве"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="Статус документа",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата и время загрузки документа"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата и время проверки")),
                ("review_comment", models.TextField(blank=True, verbose_name="Комментарий при проверке")),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
                "ordering": ["-uploaded_at"],
                "permissions": [
                    ("view_all_documents", "Может видеть все документы"),
                    ("can_approve_document", "Может подтверждать документы"),
                    ("can_reject_document", "Может отклонять документы"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        default="Мои документы",
                        help_text="Заполните название папки",
                        max_length=100,
                        verbose_name="Название папки",
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Идентификатор")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Папка",
                "verbose_name_plural": "Папки",
            },
        ),
        migrations.CreateModel(
            name="QueueItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0, unique=True, verbose_name="Позиция в очереди")),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время и дата добавления документа в очередь"
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ в очереди",
                "verbose_name_plural": "Документы в очереди",
                "ordering": ["position"],
            },
        ),
    ]
