# Generated by Django 5.2.5 on 2025-09-02 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalqueue",
            name="approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_queue",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Администратор",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="assigned_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный администратор",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                help_text="Укажите владельца документа",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Проверивший администратор",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together={("title",)},
        ),
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="documents.folder",
                verbose_name="Папка",
            ),
        ),
        migrations.AddField(
            model_name="queueitem",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_items",
                to="documents.document",
                verbose_name="Документ",
            ),
        ),
        migrations.AddField(
            model_name="queueitem",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="documents.approvalqueue",
                verbose_name="Очередь",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="queueitem",
            unique_together={("queue", "document"), ("queue", "position")},
        ),
    ]
