# Generated by Django 5.2.5 on 2025-09-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalqueue",
            name="is_stop",
            field=models.BooleanField(default=False, verbose_name="Остановка очереди"),
        ),
        migrations.AlterField(
            model_name="document",
            name="reviewed_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="Дата и время проверки"),
        ),
    ]
