# Generated by Django 5.2.5 on 2025-09-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_approvalqueue_is_stop_alter_document_reviewed_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="queueitem",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="queueitem",
            name="position",
            field=models.PositiveIntegerField(default=0, verbose_name="Позиция в очереди"),
        ),
        migrations.AddConstraint(
            model_name="queueitem",
            constraint=models.UniqueConstraint(fields=("queue", "document"), name="unique_document_in_queue"),
        ),
        migrations.AddConstraint(
            model_name="queueitem",
            constraint=models.UniqueConstraint(fields=("queue", "position"), name="unique_position_in_queue"),
        ),
    ]
