# Generated by Django 5.2.5 on 2025-09-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_alter_queueitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="folder",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На рассмотрении"),
                    ("approved", "Одобрен"),
                    ("rejected", "Отклонен"),
                    ("archived", "В архиве"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Статус документа",
            ),
        ),
    ]
