# Generated by Django 5.2.5 on 2025-09-04 04:04

from django.db import migrations, models

import documents.services


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_alter_folder_unique_together_alter_document_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="reviewed_by",
        ),
        migrations.AddField(
            model_name="document",
            name="file_answer",
            field=models.FileField(
                blank=True,
                help_text="Файл для отправки пользователю в качестве ответа",
                null=True,
                upload_to=documents.services.DocumentFilePathGeneratorService.admin_document_path,
                verbose_name="Файл ответа администратора",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="temp_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=documents.services.DocumentFilePathGeneratorService.temp_upload_path,
                verbose_name="Временный файл",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                help_text="Введите название файла",
                upload_to=documents.services.DocumentFilePathGeneratorService.user_document_path,
                verbose_name="Расположение vs название файла",
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="slug",
            field=models.SlugField(max_length=20, unique=True, verbose_name="Идентификатор"),
        ),
    ]
