# Generated by Django 5.2.5 on 2025-09-04 10:20

from django.db import migrations, models

import documents.services


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_remove_document_reviewed_by_document_file_answer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file_answer",
        ),
        migrations.RemoveField(
            model_name="document",
            name="temp_file",
        ),
        migrations.AddField(
            model_name="queueitem",
            name="file_answer",
            field=models.FileField(
                blank=True,
                help_text="Файл для отправки пользователю в качестве ответа",
                null=True,
                upload_to=documents.services.DocumentFilePathGeneratorService.admin_document_path,
                verbose_name="Ответный файл администратора",
            ),
        ),
        migrations.AddField(
            model_name="queueitem",
            name="temp_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=documents.services.DocumentFilePathGeneratorService.temp_upload_path,
                verbose_name="Временный файл",
            ),
        ),
    ]
