# Generated by Django 5.2.5 on 2025-09-04 10:30

from django.db import migrations, models

import documents.services


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_remove_document_file_answer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="review_comment",
        ),
        migrations.RemoveField(
            model_name="queueitem",
            name="temp_file",
        ),
        migrations.AddField(
            model_name="document",
            name="temp_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=documents.services.DocumentFilePathGeneratorService.temp_upload_path,
                verbose_name="Временный файл",
            ),
        ),
        migrations.AddField(
            model_name="queueitem",
            name="review_comment",
            field=models.TextField(blank=True, verbose_name="Комментарий при проверке"),
        ),
    ]
