# Generated by Django 5.2.5 on 2025-09-04 11:00

import documents.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_remove_document_review_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="queueitem",
            name="file_answer",
        ),
        migrations.RemoveField(
            model_name="queueitem",
            name="review_comment",
        ),
        migrations.AddField(
            model_name="document",
            name="file_answer",
            field=models.FileField(
                blank=True,
                help_text="Файл для отправки пользователю в качестве ответа",
                null=True,
                upload_to=documents.services.DocumentFilePathGeneratorService.admin_document_path,
                verbose_name="Ответный файл администратора",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="review_comment",
            field=models.TextField(blank=True, verbose_name="Комментарий при проверке"),
        ),
        migrations.AddField(
            model_name="queueitem",
            name="temp_file_answer",
            field=models.FileField(
                blank=True, null=True, upload_to="temp_answers/", verbose_name="Черновик файла ответа"
            ),
        ),
        migrations.AddField(
            model_name="queueitem",
            name="temp_review_comment",
            field=models.TextField(blank=True, verbose_name="Черновик комментария"),
        ),
    ]
