# Generated by Django 5.2.5 on 2025-09-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_remove_queueitem_file_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время проверки"),
        ),
        migrations.AlterField(
            model_name="queueitem",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Добавлен в очередь"),
        ),
        migrations.AlterField(
            model_name="queueitem",
            name="position",
            field=models.PositiveIntegerField(default=0, help_text="Позиция в очереди", verbose_name="№ п/п"),
        ),
    ]
