# Generated by Django 5.2.5 on 2025-09-07 10:16

import django.db.models.deletion
from django.db import migrations, models

import documents.services


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_document_reviewed_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "file",
                    models.FileField(
                        help_text="Введите название файла",
                        upload_to=documents.services.DocumentFilePathGeneratorService.user_document_path,
                        verbose_name="Расположение vs название файла",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("original_name", models.CharField(max_length=255)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="files", to="documents.document"
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
