# Generated by Django 5.2.5 on 2025-09-07 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_documentfile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentfile",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_files",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец файла",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="additional_files", to="documents.document"
            ),
        ),
    ]
