# Generated by Django 5.2.5 on 2025-09-07 15:03

from django.db import migrations, models

import documents.services


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0013_documentfile_owner_alter_document_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="temp_file",
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Введите название файла",
                null=True,
                upload_to=documents.services.DocumentFilePathGeneratorService.user_document_path,
                verbose_name="Расположение vs название файла",
            ),
        ),
    ]
