# Generated by Django 5.2.5 on 2025-09-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0014_remove_document_temp_file_alter_document_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="file",
        ),
    ]
