# Generated by Django 5.2.5 on 2025-09-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0015_remove_document_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_answer",
            field=models.FileField(
                blank=True,
                help_text="Файл для отправки пользователю в качестве ответа",
                null=True,
                upload_to="DocumentFilePathGeneratorService.admin_document_path",
                verbose_name="Ответный файл администратора",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(
                help_text="Укажите название документа", max_length=200, verbose_name="Наименование документа"
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="file",
            field=models.FileField(
                help_text="Загрузите файл",
                upload_to="DocumentFilePathGeneratorService.user_document_path",
                verbose_name="Расположение vs название файла",
            ),
        ),
    ]
