# Generated by Django 5.2.5 on 2025-09-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0016_alter_document_file_answer_alter_document_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="queueitem",
            options={
                "ordering": ["position"],
                "permissions": [
                    ("can_review_documents", "Может проверять документы"),
                    ("can_upload_answer_file", "Может загружать ответные файлы"),
                ],
                "verbose_name": "Документ в очереди",
                "verbose_name_plural": "Документы в очереди",
            },
        ),
    ]
