# Generated by Django 5.2.5 on 2025-09-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0017_alter_queueitem_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_answer",
            field=models.FileField(
                blank=True,
                help_text="Файл для отправки пользователю в качестве ответа",
                null=True,
                upload_to="documents.services.DocumentFilePathGeneratorService.admin_document_path",
                verbose_name="Ответный файл администратора",
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="file",
            field=models.FileField(
                help_text="Загрузите файл",
                upload_to="documents.services.DocumentFilePathGeneratorService.user_document_path",
                verbose_name="Расположение vs название файла",
            ),
        ),
        migrations.AlterField(
            model_name="queueitem",
            name="temp_file_answer",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents.services.DocumentFilePathGeneratorService.admin_document_path",
                verbose_name="Черновик файла ответа",
            ),
        ),
    ]
