# Generated by Django 5.2.5 on 2025-09-16 16:45

import documents.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0018_alter_document_file_answer_alter_documentfile_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file_answer",
            field=models.FileField(
                blank=True,
                help_text="Файл для отправки пользователю в качестве ответа",
                null=True,
                upload_to=documents.services.DocumentFilePathGeneratorService.admin_document_path,
                verbose_name="Ответный файл администратора",
            ),
        ),
        migrations.AlterField(
            model_name="documentfile",
            name="file",
            field=models.FileField(
                help_text="Загрузите файл",
                upload_to=documents.services.DocumentFilePathGeneratorService.user_document_path,
                verbose_name="Расположение vs название файла",
            ),
        ),
        migrations.AlterField(
            model_name="queueitem",
            name="temp_file_answer",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=documents.services.DocumentFilePathGeneratorService.admin_document_path,
                verbose_name="Черновик файла ответа",
            ),
        ),
    ]
