# Generated by Django 5.2.5 on 2025-09-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0019_alter_document_file_answer_alter_documentfile_file_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-uploaded_at"],
                "permissions": [
                    ("can_approve_document", "Может подтверждать документы"),
                    ("can_reject_document", "Может отклонять документы"),
                ],
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
    ]
