# Generated by Django 5.2.5 on 2025-09-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0020_alter_document_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalqueue",
            name="title",
            field=models.CharField(
                default="Документы в работе 2025-09-20 20:24:35.662444+03:00",
                help_text="Укажите название очереди",
                max_length=200,
                verbose_name="Название очереди",
            ),
        ),
    ]
