# Generated by Django 5.2.5 on 2026-08-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0022_alter_approvalqueue_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalqueue",
            name="title",
            field=models.CharField(
                default="Документы в работе 2026-08-06 18:58:35.380135+03:00",
                help_text="Укажите название очереди",
                max_length=200,
                verbose_name="Название очереди",
            ),
        ),
    ]
